name: PR

on:
  workflow_dispatch:  # TODO: for debugging
  pull_request:

concurrency:
  # group by workflow and ref; the last slightly strange component ensures that for pull
  # requests, we limit to 1 concurrent job, but for the master branch we don't
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/master' || github.run_number }}
  # Cancel intermediate builds, but only if it is a pull request build.
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  detect-changes:
    name: "Detect packages that were added, removed or modified"
    runs-on: ubuntu-18.04
    outputs:
      remove-matrix: ${{ steps.detect-changes.outputs.remove-matrix }}
      update-matrix: ${{ steps.detect-changes.outputs.update-matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5

      - name: "Determine what was added and what removed"
        id: detect-changes
        run: |
            # turn off rename detection here, so we see renmes as "remove + add"
            # and thus propertly detect if other packages depend on the old name
            added=$(git diff --name-only --no-renames --diff-filter=A HEAD^ -- | xargs dirname)
            deleted=$(git diff --name-only --no-renames --diff-filter=D HEAD^ -- | xargs dirname)
            modified=$(git diff --name-only --no-renames --diff-filter=M HEAD^ -- | xargs dirname)

            echo "Packages deleted: $deleted"

            MATRIX="{\"package\":["
            for PKG in ${deleted}; do
              echo "${PKG}"
              MATRIX="${MATRIX}\"${PKG}\","
            done
            MATRIX="${MATRIX}]}"
            echo "::set-output name=remove-matrix::$MATRIX"

            echo "Packages added: $added"
            echo "Packages modified: $modified"
            MATRIX="{\"package\":["
            for PKG in ${added} ${modified}; do
              echo "${PKG}"
              MATRIX="${MATRIX}\"${PKG}\","
            done
            MATRIX="${MATRIX}]}"
            echo "::set-output name=update-matrix::$MATRIX"

  remove-package:
    name: "Remove ${{ matrix.package }}"
    needs: detect-changes
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect-changes.outputs.remove-matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: "Clone package distribution tools"
        run: git clone https://github.com/gap-system/PackageDistroTools

      - name: "TODO"
        run: echo "TODO"

  add-or-update-package:
    name: "Add or update ${{ matrix.package }}"
    needs: detect-changes
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect-changes.outputs.update-matrix) }}
    steps:
      - uses: actions/checkout@v2

      - name: "Clone package distribution tools"
        run: git clone https://github.com/gap-system/PackageDistroTools

      - name: "TODO"
        run: echo "TODO"
